(function() {
/*
 domready (c) Dustin Diaz 2012 - License MIT
 v0.3.0 (https://github.com/ded/domready/tree/v0.3.0)
*/
var A="function"==typeof Object.defineProperties?Object.defineProperty:function(g,f,d){g!=Array.prototype&&g!=Object.prototype&&(g[f]=d.value)},G="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function H(){H=function(){};G.Symbol||(G.Symbol=I)}var J=0;function I(g){return"jscomp_symbol_"+(g||"")+J++}
function K(){H();var g=G.Symbol.iterator;g||(g=G.Symbol.iterator=G.Symbol("iterator"));"function"!=typeof Array.prototype[g]&&A(Array.prototype,g,{configurable:!0,writable:!0,value:function(){return L(this)}});K=function(){}}function L(g){var f=0;return M(function(){return f<g.length?{done:!1,value:g[f++]}:{done:!0}})}function M(g){K();g={next:g};g[G.Symbol.iterator]=function(){return this};return g}function N(g){K();var f=g[Symbol.iterator];return f?f.call(g):L(g)}
function O(g,f){if(f){for(var d=G,l=g.split("."),c=0;c<l.length-1;c++){var n=l[c];n in d||(d[n]={});d=d[n]}l=l[l.length-1];c=d[l];n=f(c);n!=c&&null!=n&&A(d,l,{configurable:!0,writable:!0,value:n})}}
O("Promise",function(g){function f(c){this.g=0;this.A=void 0;this.b=[];var n=this.v();try{c(n.resolve,n.reject)}catch(q){n.reject(q)}}function d(){this.b=null}if(g)return g;d.prototype.g=function(c){this.b||(this.b=[],this.v());this.b.push(c)};d.prototype.v=function(){var c=this;this.l(function(){c.A()})};var l=G.setTimeout;d.prototype.l=function(c){l(c,0)};d.prototype.A=function(){for(;this.b&&this.b.length;){var c=this.b;this.b=[];for(var d=0;d<c.length;++d){var f=c[d];delete c[d];try{f()}catch(x){this.w(x)}}}this.b=
null};d.prototype.w=function(c){this.l(function(){throw c;})};f.prototype.v=function(){function c(c){return function(n){f||(f=!0,c.call(d,n))}}var d=this,f=!1;return{resolve:c(this.Ka),reject:c(this.w)}};f.prototype.Ka=function(c){if(c===this)this.w(new TypeError("A Promise cannot resolve to itself"));else if(c instanceof f)this.Ra(c);else{a:switch(typeof c){case "object":var d=null!=c;break a;case "function":d=!0;break a;default:d=!1}d?this.Fa(c):this.V(c)}};f.prototype.Fa=function(c){var d=void 0;
try{d=c.then}catch(q){this.w(q);return}"function"==typeof d?this.Za(d,c):this.V(c)};f.prototype.w=function(c){this.Y(2,c)};f.prototype.V=function(c){this.Y(1,c)};f.prototype.Y=function(c,d){if(0!=this.g)throw Error("Cannot settle("+c+", "+d|"): Promise already settled in state"+this.g);this.g=c;this.A=d;this.Ea()};f.prototype.Ea=function(){if(this.b){for(var c=this.b,d=0;d<c.length;++d)c[d].call(),c[d]=null;this.b=null}};var c=new d;f.prototype.Ra=function(c){var d=this.v();c.l(d.resolve,d.reject)};
f.prototype.Za=function(c,d){var f=this.v();try{c.call(d,f.resolve,f.reject)}catch(x){f.reject(x)}};f.prototype.then=function(c,d){function g(c,d){return"function"==typeof c?function(d){try{n(c(d))}catch(C){l(C)}}:d}var n,l,z=new f(function(c,d){n=c;l=d});this.l(g(c,n),g(d,l));return z};f.prototype["catch"]=function(c){return this.then(void 0,c)};f.prototype.l=function(d,f){function g(){switch(l.g){case 1:d(l.A);break;case 2:f(l.A);break;default:throw Error("Unexpected state: "+l.g);}}var l=this;
this.b?this.b.push(function(){c.g(g)}):c.g(g)};f.resolve=function(c){return c instanceof f?c:new f(function(d){d(c)})};f.reject=function(c){return new f(function(d,f){f(c)})};f.g=function(c){return new f(function(d,g){for(var l=N(c),n=l.next();!n.done;n=l.next())f.resolve(n.value).l(d,g)})};f.b=function(c){var d=N(c),g=d.next();return g.done?f.resolve([]):new f(function(c,l){function n(d){return function(f){q[d]=f;r--;r||c(q)}}var q=[],r=0;do q.push(void 0),r++,f.resolve(g.value).l(n(q.length-1),
l),g=d.next();while(!g.done)})};f.$jscomp$new$AsyncExecutor=function(){return new d};return f});
O("String.prototype.startsWith",function(g){return g?g:function(f,d){if(null==this)throw new TypeError("The 'this' value for String.prototype.startsWith must not be null or undefined");if(f instanceof RegExp)throw new TypeError("First argument to String.prototype.startsWith must not be a regular expression");var g=this+"";f+="";for(var c=g.length,n=f.length,z=Math.max(0,Math.min(d|0,g.length)),q=0;q<n&&z<c;)if(g[z++]!=f[q++])return!1;return q>=n}});
(function(){window.zaius||(window.zaius={});if(!window.zaius.loaded){!function(a,b){this[a]=b()}("domready",function(a){function b(){var a;for(g=1;a=e.shift();)a()}var e=[],c,k=document,d=k.documentElement,f=d.doScroll,g=(f?/^loaded|^c/:/^loaded|c/).test(k.readyState);k.addEventListener&&k.addEventListener("DOMContentLoaded",c=function(){k.removeEventListener("DOMContentLoaded",c,!1);b()},!1);f&&k.attachEvent("onreadystatechange",c=function(){/^c/.test(k.readyState)&&(k.detachEvent("onreadystatechange",
c),b())});return a=f?function(b){self!=top?g?b():e.push(b):function(){try{d.doScroll("left")}catch(R){return setTimeout(function(){a(b)},50)}b()}()}:function(a){g?a():e.push(a)}});var g={trackerUrl:window.location.protocol+"//jumbe.zaius.com",visitorCookieExpiryDays:730,referrerCookieExpiryDays:60,cookieDomain:"",idSyncs:{},includeQueryString:!1,includeHash:!1,convertParameters:!1,webPushConfigs:{}},f=window.JSON;"object"!==typeof f&&(f={});(function(){function a(a){return 10>a?"0"+a:a}function b(a){k.lastIndex=
0;return k.test(a)?'"'+a.replace(k,function(a){var b=l[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function e(a,c){var h,k,f=d,p=c[a];p&&"object"===typeof p&&"function"===typeof p.toJSON&&(p=p.toJSON(a));"function"===typeof n&&(p=n.call(c,a,p));switch(typeof p){case "string":return b(p);case "number":return isFinite(p)?String(p):"null";case "boolean":case "null":return String(p);case "object":if(!p)return"null";d+=g;var l=[];if("[object Array]"===
Object.prototype.toString.apply(p)){var r=p.length;for(h=0;h<r;h+=1)l[h]=e(h,p)||"null";var m=l.length?d?"[\n"+d+l.join(",\n"+d)+"\n"+f+"]":"["+l.join(",")+"]":"[]";d=f;return m}if(n&&"object"===typeof n)for(r=n.length,h=0;h<r;h+=1)"string"===typeof n[h]&&(k=n[h],(m=e(k,p))&&l.push(b(k)+(d?": ":":")+m));else for(k in p)Object.prototype.hasOwnProperty.call(p,k)&&(m=e(k,p))&&l.push(b(k)+(d?": ":":")+m);m=l.length?d?"{\n"+d+l.join(",\n"+d)+"\n"+f+"}":"{"+l.join(",")+"}":"{}";d=f;return m}}"function"!==
typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var c,k,d,g,l,n;"function"!==typeof f.stringify&&(k=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
l={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},f.stringify=function(a,b,c){var h;g=d="";if("number"===typeof c)for(h=0;h<c;h+=1)g+=" ";else"string"===typeof c&&(g=c);if((n=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("JSON.stringify");return e("",{"":a})});"function"!==typeof f.parse&&(c=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,f.parse=function(a,b){function e(a,
c){var h,k,d=a[c];if(d&&"object"===typeof d)for(h in d)Object.prototype.hasOwnProperty.call(d,h)&&(k=e(d,h),void 0!==k?d[h]=k:delete d[h]);return b.call(a,c,d)}var h;a=String(a);c.lastIndex=0;c.test(a)&&(a=a.replace(c,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return h=eval("("+
a+")"),"function"===typeof b?e({"":h},""):h;throw new SyntaxError("JSON.parse");})})();var d={a:null,I:null,L:!1,R:!0,initialize:function(a,b){this.L=!1;this.I=null;this.a=c.clone(g);this.m=this.VUID=window.zaius.VUID=void 0;l.c=0;if(!c.i(a))throw Error("Your Zaius supplied tracker ID is required");if(null!==b&&"undefined"!==typeof b)if("object"!==typeof b)console.error("Zaius ignoring config object, type is "+typeof b);else{for(var e in b)b.hasOwnProperty(e)&&!g.hasOwnProperty(e)&&console.error("Zaius ignoring unrecognized config field: "+
e);this.a=c.j(this.a,b)}this.Ha();this.I=a;this.L=!0;this.Ia=this.Ca();this.VUID=window.zaius.VUID=this.ab();this.m=this.U();this.a.hasOwnProperty("idSyncs")&&this.Va(this.a.idSyncs);this.a.hasOwnProperty("webPushConfigs")&&this.na(this.a.webPushConfigs)},entity:function(a,b){if(null===b||void 0===b)b={};var e=this.aa(a+"_dimension");return this.P(c.s(c.j(e,b)))},event:function(a,b){if(null===b||void 0===b)b={};var e=this.aa(a),h=l.qa(),k=this.Wa();return this.P(c.s(c.j(h,k,e,b)))},subscribe:function(a,
b,e){function h(a){e&&c.X(e)&&e(a)}if(c.o(a))if(c.Da(a.email))if(c.i(a.list_id)&&0!==a.list_id.length){var k=c.s(a);delete k.list_id;k=c.compact(k);1<c.Ja(k)&&this.entity("customer",k);this.event("list",c.j(a,{action:"subscribe"}));b&&c.X(b)&&b()}else h("invalid list_id "+a.list_id);else h("invalid email "+a.email);else h("subscribe takes an object with required fields 'list_id' and 'email'")},identify:function(a){c.i(a)&&""!==c.Ya(a)&&d.da(a)},anonymize:function(){void 0!==d.m&&(d.VUID=window.zaius.VUID=
d.K());d.m=void 0;c.setCookie("z_customer_id","",-100,"")},P:function(a){this.L&&(l.za(a)&&d.da(a.customer_id),this.send(a))},O:function(){var a=Array.prototype.slice.call(arguments),b=a.shift(),e=a.shift(),h;if(!b||"string"!==typeof b)return c.console.warn("[ZAIUS] Plugin name argument is missing or not a string:",b),!1;if(!e)return c.console.warn("[ZAIUS] Plugin function name argument is missing"),!1;var k=b.split(".");var f=d[k[0]]||window.zaius[k[0]];for(h=1;h<k.length;h++){if(!f)return c.console.warn("[ZAIUS] Plugin is missing:",
b),!1;f=f[k[h]]}if(f){if((k=f[e])&&"function"===typeof k)return k.apply(f,a),!0;c.console.warn("[ZAIUS] Plugin function argument is missing or not a function:",b,e);return!1}c.console.warn("[ZAIUS] Plugin is missing:",b);return!1},aa:function(a){return c.compact({zaius_js_version:"2.3.2",tracker_id:this.I,event_type:a})},Wa:function(){var a=this.Ia&&this.R;delete this.R;var a={vuid:this.VUID,customer_id:d.m,new_user:a?1:0},b=this.D();b&&(a[b.J+"_"+b.platform+"_push_tokens"]=b.B);return c.compact(a)},
ab:function(){var a=this.G(this.C("vuid")),b=a[0],e=c.f("zaiusVuid"),h=""+(new Date).getTime(),k=this.a.visitorCookieExpiryDays,d=this.a.cookieDomain;l.c=l.c?l.c:a[1];e&&c.W(e)&&(b=e);b&&c.W(b)||(b=c.T());c.setCookie("vuid",b+"|"+h,k,d);return b},U:function(){var a=this.G(this.C("z_customer_id")),b=a[0],e=""+(new Date).getTime(),h=this.a.visitorCookieExpiryDays,d=this.a.cookieDomain;l.c=l.c?l.c:a[1];void 0!==b&&c.setCookie("z_customer_id",b+"|"+e,h,d);return b},da:function(a){var b=this.G(this.C("vuid")),
e=""+(new Date).getTime(),h=this.a.visitorCookieExpiryDays,k=this.a.cookieDomain;l.c=l.c?l.c:b[1];if(void 0!==a&&null!==a&&""!==a&&"undefined"!==a)return void 0!==d.m&&d.m!=a.toString()&&(d.VUID=window.zaius.VUID=d.K()),d.m=a.toString(),c.setCookie("z_customer_id",a+"|"+e,h,k),a},K:function(){var a=this.G(this.C("vuid")),b=""+(new Date).getTime(),e=this.a.visitorCookieExpiryDays,h=this.a.cookieDomain,d=c.T();l.c=l.c?l.c:a[1];c.setCookie("vuid",d+"|"+b,e,h);return d},G:function(a){var b=void 0,e=0;
if(a)try{var c=a.split("|"),b=c[0],e=c[1]}catch(k){}return[b,e]},C:function(a){var b,e=document.cookie.split(";"),h=[];for(b=0;b<e.length;b++){var d=e[b].substr(0,e[b].indexOf("="));var f=e[b].substr(e[b].indexOf("=")+1);d=d.replace(/^\s+|\s+$/g,"");if(d==a)try{h.push(decodeURIComponent(f))}catch(Q){h.push(unescape(f))}}1<h.length&&(c.setCookie(a,"",-100,window.location.hostname),c.setCookie(a,"",-100,""));return 0<h.length?h[h.length-1]:void 0},send:function(a){a=c.$(a);(new Image(1,1)).src=encodeURI(this.a.trackerUrl+
"/zaius.gif?")+a},ca:function(a){(new Image(1,1)).src=encodeURI(a)},Ca:function(){return!c.getCookie("vuid")},Pa:function(){var a=[];if(c.isArray(window.zaius)){for(var b=window.zaius,e=0;e<b.length;e++)if("initialize"===b[e][0]){var h=b[e];b.splice(e,1);b.unshift(h);break}for(e=0;e<b.length;e++)try{var d=b[e].shift();"initialize"===d?this.initialize.apply(this,b[e]):"onload"===d?a.push(b[e]):"entity"===d?this.entity.apply(this,b[e]):"event"===d?this.event.apply(this,b[e]):"identify"===d?this.identify.apply(this,
b[e]):"anonymize"===d?this.anonymize.apply(this,b[e]):"dispatch"===d&&this.O.apply(this,b[e])}catch(p){}}return a},Ha:function(){var a=c.getCookie("zaius_js_version"),b=this.a.visitorCookieExpiryDays,e=this.a.cookieDomain;void 0===a&&(a=c.getCookie("jumbe_version"),c.setCookie("jumbe_version","",-100,""));(void 0===a||c.fa(a,"0.1.8"))&&c.setCookie("vtsrc","",-100,e);void 0!==a&&!c.fa(a,"0.1.9")||"undefined"!==this.U()||(c.setCookie("z_customer_id","",-100,""),this.K());c.setCookie("zaius_js_version",
"2.3.2",b,e)},Va:function(a){var b=Math.round((new Date).getTime()/1E3),e=this.a.visitorCookieExpiryDays,h=this.a.cookieDomain,k=this.va(c.getCookie("z_idsyncs"));c.S(a,function(a,e){var c=k[a];c&&b-c.lastSynced>=e.ttl?(d.ca(d.N(e)),c.lastSynced=b):void 0===c&&(d.ca(d.N(e)),k[a]={lastSynced:b})});c.setCookie("z_idsyncs",this.Ta(k),e,h)},N:function(a){var b=this.VUID.replace(/-/g,""),e=new RegExp(a.vuidMacro.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,"\\$&"),"g");return a.url.replace(e,b)},va:function(a){var b=
{};if(a){a=a.split("\n");for(var e=0;e<a.length;e++){var c=a[e].split("\t");b[c[0]]={lastSynced:parseInt(c[1],10)}}}return b},Ta:function(a){var b="";c.S(a,function(a,c){b+=a+"\t"+c.lastSynced+"\n"});return b.substring(0,b.length-1)},na:function(a){window.zaius.webPush.baseConfigs=a;var b=!1,e;for(e in a)if(a.hasOwnProperty(e)){var c=a[e];if(!window.location.href.indexOf(c.url)){b=!0;c.autoInit&&window.zaius.webPush.initialize(c);break}}b||window.zaius.webPush.remove()},h:function(a,b,e){var c=this.D();
if(c&&c.platform==a&&c.B&&c.B!=e){var d={action:"remove_push_token",app_id:c.J};d[c.J+"_"+c.platform+"_push_tokens"]=c.B;zaius.event("push",d)}this.Ua(a,b,e)},D:function(){var a=(c.getCookie("zaius_web_push")||"").split("\n")[0].match(/([^:]+):([^:]+):(.+)/);return a?{platform:a[1],J:a[2],B:a[3]}:null},Ua:function(a,b,e){null==e?c.setCookie("zaius_web_push","",180):c.setCookie("zaius_web_push",a+":"+b+":"+e,180)}},l={title:function(){return document.title},za:function(a){return"customer_id"in a},
page:function(){var a=c.cb();!0===d.a.includeQueryString&&(a+=c.ha());!0===d.a.includeHash&&(a+=c.ga());return a},viewport:function(){var a=window.devicePixelRatio?window.devicePixelRatio:1;if(window.innerWidth){var b=(window.innerWidth*a).toFixed();var e=(window.innerHeight*a).toFixed();b=b+"x"+e}else if(e=document.documentElement||document.body)b=(e.clientWidth*a).toFixed(),e=(e.clientHeight*a).toFixed(),b=b+"x"+e;return b},Sa:function(){var a=this.viewport(),b=window.devicePixelRatio?window.devicePixelRatio:
1,b={resolution:(screen.width*b).toFixed()+"x"+(screen.height*b).toFixed(),color_depth:screen.colorDepth+"-bit"};a&&(b.viewport=a);return b},Ba:function(){var a=navigator.mimeTypes;(a=(a=a?a["application/x-java-vm"]:void 0)&&a.enabledPlugin)||(a="unknown"!==typeof navigator.javaEnabled&&c.Aa(navigator.javaEnabled)&&navigator.javaEnabled());return a},xa:function(){var a=navigator.plugins,a=a&&c.o(a["Shockwave Flash"])?a["Shockwave Flash"]:void 0,b=navigator.mimeTypes,b=(b=b?b["application/x-shockwave-flash"]:
void 0)&&b.enabledPlugin,e;if(a){var d=a.description;d&&b&&(e=d.replace(/^.*\s+(\S+\s+\S+$)/,"$1"))}else if(window.ActiveXObject){try{d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),e=d.GetVariable("$version")}catch(k){}if(!e)try{d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),e="WIN 6,0,21,0",d.eb="always",e=d.GetVariable("$version")}catch(k){}if(!e)try{d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),e=d.GetVariable("$version")}catch(k){}e&&(e=e.split(" ")[1].split(","),e=e[0]+
"."+e[1]+" r"+e[2])}return e},oa:function(){var a=this.xa(),b=navigator.language||navigator.browserLanguage,e=document.characterSet||document.charset,c={java:this.Ba()?1:0};a&&(c.flash=a);b&&(c.language=b.toLowerCase());e&&(c.character_set=e.toLowerCase());return c},Xa:function(){var a={},b={},e=this.pa();if(e)a=e;else if(document.referrer&&(e=c.Ma(document.referrer),e.hostname!==document.location.hostname)){b.referrer=e.ya;b.referral_host=e.hostname;b.referral_path=e.path;var d=n.Ga(e);d?(d.original_referral&&
(b=d.original_referral,delete d.original_referral),c.j(a,d)):(a.source=e.hostname,a.medium="referral")}return c.j(b,this.ra(a))},ra:function(a){var b=c.getCookie("vtsrc"),b=b?c.ta(b):{source:"direct",medium:"none"},e="organic"===a.medium||"cpc"===a.medium,h="referral"===a.medium,k=d.a.referrerCookieExpiryDays;if(a.isCampaign||e){b=a;var f=!0}else!h||"none"!==b.medium&&"referral"!==b.medium||(b=a,f=!0);a=c.wa(b);c.setCookie("vtsrc",a,k);a=c.s(b);this.Qa||(this.Qa=!0,f&&(a.landing=1));return a},pa:function(){var a,
b=(a=c.f("campaignSource")||c.f("utm_source"))?a.replace(/\|/g,"_"):null;if(b)return c.compact({isCampaign:!0,source:b,campaign:(a=c.f("campaignName")||c.f("utm_campaign"))?a.replace(/\|/g,"_"):null,medium:(a=c.f("campaignMedium")||c.f("utm_medium"))?a.replace(/\|/g,"_"):null,keywords:(a=c.f("campaignKeyword")||c.f("utm_term"))?a.replace(/\|/g,"_"):null,content:(a=c.f("campaignContent")||c.f("utm_content"))?a.replace(/\|/g,"_"):null})},Oa:function(){var a,b,e={};if(!this.Na&&window.performance&&(this.Na=
!0,a=window.performance.timing)){var c=function(a,b){return a&&b&&a>b&&864E5>a-b?a-b:!1};if(b=c(a.redirectEnd,a.redirectStart))e.redirect_time=b;if(b=c(a.domainLookupEnd,a.domainLookupStart))e.domain_lookup_time=b;if(b=c(a.connectEnd,a.connectStart))e.server_connect_time=b;if(b=c(a.responseStart,a.requestStart))e.server_response_time=b;if(b=c(a.responseEnd,a.responseStart))e.page_download_time=b;if(b=c(a.loadEventEnd,a.domLoading))e.page_load_time=b;if(b=c(a.loadEventEnd,a.navigationStart))e.total_load_time=
b}return e},la:864E5,sa:function(){var a={};this.c&&(a.days_since_last_visit=Math.floor(((new Date).getTime()-new Date(+this.c))/this.la));return a},ua:function(){return c.La(!0===d.a.convertParameters)},qa:function(){var a=this.ua(),b=this.Sa(),e=this.Xa(),d=this.oa(),k=this.sa(),f=this.Oa(),g=c.random(),g={hostname:window.location.hostname,page:this.page(),title:this.title(),u:g};return c.j(a,b,e,d,k,f,g)}},c={$:function(a,b){var e=[],c;for(c in a)if(a.hasOwnProperty(c)){var d=b?b+"["+c+"]":c,f=
a[c];"undefined"!==typeof f&&null!==f&&e.push("object"===typeof f?this.$(f,d):encodeURIComponent(d)+"="+encodeURIComponent(f))}return e.join("&")},f:function(a){return(a=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec(this.bb()))?decodeURIComponent(a[1])||null:null},bb:function(){return window.location.href},cb:function(){return window.location.pathname},ha:function(){return window.location.search},ga:function(){return window.location.hash},La:function(a){var b=this.ha().substr(1).split("&"),e=this.ga().substr(1).split("&"),
c=[],d={};""!=b&&(c=c.concat(b));""!=e&&(c=c.concat(e));if(c.length)for(b=0;b<c.length;b++)if(e=c[b].split("="),2===e.length){var f=decodeURIComponent(e[0]).replace(/\s+/g,"_");if(a||"zm64_id"===f||f.match(/^zaius_alias_.+/))d[f]=decodeURIComponent(e[1])}return d},getCookie:function(a){var b,e=document.cookie.split(";");for(b=0;b<e.length;b++){var c=e[b].substr(0,e[b].indexOf("="));var d=e[b].substr(e[b].indexOf("=")+1);c=c.replace(/^\s+|\s+$/g,"");if(c==a)try{return decodeURIComponent(d)}catch(p){return unescape(d)}}},
setCookie:function(a,b,e,c){b=encodeURIComponent(b)+"; ";var d=new Date;d.setDate(d.getDate()+e);d="expires="+d.toUTCString()+"; ";document.cookie=a+"="+b+d+"path=/; "+(c?"domain="+c+";":"")},T:function(){var a="",b;for(b=0;32>b;b++){var e=16*Math.random()|0;if(8==b||12==b||16==b||20==b)a+="-";a+=(12==b?4:16==b?e&3|8:e).toString(16)}return a},random:function(){return Math.round(2147483647*Math.random())},j:function(a,b){for(var e=Array.prototype.slice.call(arguments,1),c=0,d;d=e[c];c++)for(var f in d)if(this.isArray(d[f])){a[f]=
{};for(var g=0;g<d[f].length;g++)a[f][g]=d[f][g]}else a[f]=d[f];return a},fb:function(a,b,e){for(var c=0;c<b.length;c++)void 0!==a[b[c]]&&(e[b[c]]=a[b[c]]);return e},clone:function(a,b){if(!this.o(a))return a;var c={};b=b||"";for(var d in a)c[b+d]=a[d];return c},s:function(a){if(!this.o(a))return a;var b=this.isArray(a)?[]:{},c;for(c in a)a.hasOwnProperty(c)&&(b[c]=this.s(a[c]));return b},compact:function(a){if(!this.o(a))return a;for(var b in a){var c=a[b];null!==c&&void 0!==c&&c===c&&"undefined"!==
c||delete a[b]}return a},Ja:function(a){if(!this.o(a))return 0;var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b},wa:function(a){if(!this.o(a))return a;var b=[],c;for(c in a)b.push(c+"="+a[c]);return b.join("|")},ta:function(a){if(!this.i(a))return a;var b={};a=a.split(/\|/g);for(var c=0;c<a.length;c++){var d=a[c].split(/=/);b[d[0]]=d[1]}return b},i:function(a){return"[object String]"==Object.prototype.toString.call(a)},Ya:function(a){return this.i(a)?a.replace(/^\s\s*/,"").replace(/\s\s*$/,
""):a},W:function(a){return this.i(a)&&/^[\x00-\x7F]*$/.test(a)},o:function(a){return a===Object(a)},isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)},X:function(a){return"function"===typeof a},Aa:function(a){return void 0!==a},ia:/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,Da:function(a){return this.i(a)&&a.match(this.ia)&&255>a.length},S:function(a,b){var c=[],d=[],f;for(f in a)a.hasOwnProperty(f)&&(c.push(f),d.push(a[f]));for(f=0;f<c.length;f++)b(c[f],d[f])},ma:/^(([^:\/?#]+):)?(\/\/([^\/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?/,
Ma:function(a){if(this.i(a)){var b=a.match(this.ma);return{ya:a,protocol:b[2],hostname:b[4],path:b[5],Z:b[7]?decodeURIComponent(b[7]):""}}},fa:function(a,b){var c=a.split("."),d=b.split("."),c=[+c[0],+c[1],+c[2]],d=[+d[0],+d[1],+d[2]];return c[0]>d[0]?!1:c[0]<d[0]?!0:c[1]>d[1]?!1:c[1]<d[1]?!0:c[2]<d[2]},console:{log:function(){},info:function(){},warn:function(){},error:function(){}}};(function(a){var b=["log","info","warn","error"],e;for(e=0;e<b.length;e++)a&&a[b[e]]&&(c.console[b[e]]=a[b[e]].bind(a))})(window.console);
var n={ka:/^(.*\.)?(daum|eniro|naver|google|googleadservices|yahoo|msn|bing|aol|lycos|ask|altavista|netscape|cnn|about|mamma|alltheweb|voila|virgilio|baidu|alice|yandex|najdi|seznam|search|wp|onetcenter|szukacz|yam|pchome|kvasir|sesam|ozu|terra|mynet|ekolay|rambler)\.[^\.]{2,3}(\.[^\.]{2})?$/,ja:{daum:["q"],eniro:["search_word"],naver:["query"],google:["q"],googleadservices:["q"],yahoo:["p"],msn:["q"],bing:["q"],aol:["query","q"],lycos:["query"],ask:["q"],altavista:["q"],netscape:["query"],cnn:["query"],
about:["terms"],mamma:["query"],alltheweb:["q"],voila:["rdata"],virgilio:["qs"],baidu:["wd"],alice:["qs"],yandex:["text"],najdi:["q"],seznam:["q"],search:["q"],wp:["szukaj"],onetcenter:["qt"],szukacz:["q"],yam:["k"],pchome:["q"],kvasir:["q"],sesam:["q"],ozu:["q"],terra:["query"],mynet:["q"],ekolay:["q"],rambler:["words"]},Ga:function(a){if(!this.ba){var b=a.hostname.match(this.ka);if(b&&b[2]){for(var b=b[2],e=this.ja[b],d,f=0;f<e.length;f++){var g=a.Z.match(new RegExp("[\\?&]"+e[f]+"=([^&]*)"));if(g){d=
g[1];break}}var l,e="organic";if("google"==b||"googleadservices"==b)f=a.path.split("/"),"aclk"==f[f.length-1]&&(e="cpc","googleadservices"==b&&(b="google",(a=a.Z.match(/[\?&]ohost=([^&]*)/))&&a[1]&&(l={referrer:a[1],referral_host:a[1],referral_path:""})));this.ba=c.compact({source:b,medium:e,keywords:d,original_referral:l})}}return this.ba}},z=function(){window.zaius.initialize=function(a,b){d.initialize(a,b);return this};window.zaius.onload=function(a){a instanceof Function&&setTimeout(a,0)};window.zaius.entity=
function(a,b){d.entity(a,b);return this};window.zaius.event=function(a,b){d.event(a,b);return this};window.zaius.subscribe=function(a,b,c){d.subscribe(a,b,c);return this};window.zaius.identify=function(a){d.identify(a);return this};window.zaius.anonymize=function(){d.anonymize();return this};window.zaius.dispatch=function(){d.O.apply(d,arguments);return this};window.zaius.utils={getCookie:c.getCookie,setCookie:c.setCookie}};domready(function(){setTimeout(function(){var a=d.Pa();z();for(var b=0;b<
a.length;b++)if(a[b][0]instanceof Function)a[b][0]()},0)});if(!(window.zaius.initialize instanceof Function)){zaius=window.zaius=[];zaius.methods="initialize onload entity event subscribe identify anonymize dispatch".split(" ");zaius.b=function(a){return function(){var b=Array.prototype.slice.call(arguments);b.unshift(a);zaius.push(b);return zaius}};for(var q=0;q<zaius.methods.length;q++){var x=zaius.methods[q];zaius[x]=zaius.b(x)}}window.zaius.loaded=!0;var B;(function(){function a(){B.F();c.setCookie("zaiusPushSubscribeDismissedUntil",
((new Date).getTime()+1E3*m.cancelDuration).toString(),30)}function b(){clearTimeout(x);t.style.transform="translateY("+("-"+(t.offsetHeight-parseInt(1.5*parseInt(m.fontSize,10)+15+"px",10))+"px")+") translateZ(0)";y.style.display="block";y.style.opacity=1;c.setCookie("zaiusPushSubscribePopped",(new Date).getTime().toString(),30)}function d(){t.style.opacity="0";t.style.pointerEvents="none";document.body.appendChild(v);setTimeout(function(){t.style.pointerEvents="auto";t.style.opacity="1";a:{try{var a=
c.getCookie("zaiusPushSubscribePopped");if(a&&(a=parseInt(a,10))){var d=(new Date).getTime()>a+1E3*parseInt(m.showFrequency,10);break a}}catch(P){console.error(P)}d=!0}d&&(b(),x=setTimeout(q,1E3*parseInt(m.autoHideDelay,10)))},1E3*parseInt(m.showDelay,10))}function f(){y=document.createElement("div");w(y.style,w(u(),{position:"absolute",right:"0",top:"0",padding:"10px 15px",color:m.titleColor,opacity:0,transition:"opacity 250ms",display:"none",cursor:"pointer"}));y.innerHTML="&times;";y.addEventListener("mousedown",
q);y.addEventListener("mouseover",function(a){a.stopPropagation();a.preventDefault()});y.addEventListener("mousemove",function(a){a.stopPropagation();a.preventDefault()});y.addEventListener("mouseout",function(a){a.stopPropagation();a.preventDefault()});return y}function k(){var a=document.createElement("div");w(a.style,w(u(),{padding:"10px 20px 5px 20px",color:m.titleColor}));a.textContent=m.titleText;return a}function g(){var a=document.createElement("div");w(a.style,w(u(),{padding:"0 5px 5px 5px",
color:m.bodyColor}));a.textContent=m.bodyText;return a}function l(){var a=document.createElement("div");a.id="zaius_subscribe_ui";a.style.padding="10px";var b=document.createElement("div");w(b.style,w(u(),{display:"inline-block",padding:"8px 35px",background:m.buttonBackground,color:m.buttonColor,border:m.buttonBorder,cursor:"pointer",transition:"all 100ms"}));b.textContent=m.buttonText;a.appendChild(b);a.addEventListener("click",z);b.addEventListener("mouseover",function(){b.style.background=m.buttonHoverBackground;
b.style.color=m.buttonHoverColor;b.style.border=m.buttonHoverBorder});b.addEventListener("mouseout",function(){b.style.background=m.buttonBackground;b.style.color=m.buttonColor;b.style.border=m.buttonBorder});return a}function n(){var b=document.createElement("div"),c=document.createElement("div");w(c.style,w(u(),{display:"inline-block",padding:"10px",color:m.cancelColor,"font-size":.8*parseInt(m.fontSize,10)+"px",cursor:"pointer"}));c.textContent=m.cancelText;c.addEventListener("click",a);b.appendChild(c);
return c}function r(){clearTimeout(x);x=setTimeout(q,1E3*parseInt(m.autoHideDelay,10))}function q(){t.style.transform="translateY(0) translateZ(0)";y.style.opacity=0;y.style.display="none";clearTimeout(x)}function u(){return{"font-family":m.fontFamily,"font-weight":m.fontWeight,"font-size":parseInt(m.fontSize,10)+"px","-webkit-font-smoothing":"initial","letter-spacing":"1px","box-sizing":"content-box"}}function w(a,b){if("object"===typeof b&&"object"===typeof a)for(var c in b)b.hasOwnProperty(c)&&
(a[c]=b[c]);return a}var v,t,y,z,x,m={enabled:!0,position:"left",fontFamily:'"Helvetica Neue", Arial, sans-serif',fontWeight:"200",fontSize:14,background:"rgba(0,0,0,.85)",titleText:"Looking for exclusive deals?",titleColor:"#e1e1e1",bodyText:"Subscribe to browser notifications",bodyColor:"#e1e1e1",buttonText:"SUBSCRIBE",buttonColor:"#e1e1e1",buttonBorder:"1px solid #e1e1e1",buttonBackground:"",buttonHoverBackground:"",buttonHoverColor:"#ffffff",buttonHoverBorder:"1px solid #ffffff",cancelColor:"#d1d1d1",
cancelText:"Maybe Later",cancelDuration:1200,showDelay:3,showFrequency:300,autoHideDelay:10};B={F:function(){v&&t&&(t.style.opacity="0",setTimeout(function(){t.style.opacity="1";v.remove()},1E3))},ea:function(a){try{w(m,window.zaius.webPush.config.subscribeUI)}catch(D){console.log(D)}var e;if(e=m.enabled){a:{try{var h=c.getCookie("zaiusPushSubscribeDismissedUntil");if(h&&(h=parseInt(h,10))){var p=(new Date).getTime()<h;break a}}catch(D){console.error(D)}p=!1}e=!p}if(e)if(z=a,v)v.parentNode||document.body.appendChild(v);
else try{var q=document.createElement("div");w(q.style,{position:"fixed","z-index":"2000000000",bottom:1.5*parseInt(m.fontSize,10)+15+"px",right:"right"===m.position?"20px":void 0,left:"right"!==m.position?"20px":void 0});t=document.createElement("div");w(t.style,{position:"absolute",right:"right"===m.position?0:void 0,left:"right"!==m.position?0:void 0,top:"0px",width:"350px",background:m.background,"border-radius":"2px","text-align":"center",transform:"translateY(0) translateZ(0)",transition:"transform 250ms ease-out,opacity 500ms"});
t.appendChild(f());t.appendChild(k());t.appendChild(g());t.appendChild(l());t.appendChild(n());t.addEventListener("mouseover",b);t.addEventListener("mouseout",r);q.appendChild(t);v=q;d()}catch(D){console.log(D)}}}})();var u={unsubscribe:function(){var a=window.zaius.webPush.config;return navigator.serviceWorker.ready.then(function(b){b.pushManager.getSubscription().then(function(b){if(b){var c=u.H(b);b.unsubscribe().then(function(){var b={action:"remove_push_token",app_id:a.websiteID};b[a.websiteID+
"_chrome_push_tokens"]=c;zaius.event("push",b)})["catch"](function(a){console.log("error unsubcribing",a)})}})["catch"](function(a){console.log("error fetching push notification subscription",a)})})},subscribe:function(){var a=window.zaius.webPush.config;return navigator.serviceWorker.ready.then(function(b){return b.pushManager.subscribe({userVisibleOnly:!0}).then(function(b){b=u.H(b);var c={action:"add_push_token",app_id:a.websiteID};c[a.websiteID+"_chrome_push_tokens"]=b;zaius.event("push",c);d.h("chrome",
a.websiteID,b);return"subscribed"})["catch"](function(b){if("denied"===Notification.permission)return d.h("chrome",a.websiteID,null),"denied";console.log("error subscribing for push notifications",b)})})},$a:function(a,b){return a.options&&a.options.applicationServerKey?String.fromCharCode.apply(String,new Uint8Array(a.options.applicationServerKey))===b:d.D()===u.H(a)},initialize:function(){var a=window.zaius.webPush.config;if("showNotification"in ServiceWorkerRegistration.prototype)if("denied"===
Notification.permission)d.h("chrome",a.websiteID,null);else if("PushManager"in window){if(a.platforms.chrome.autoManifest){var b=document.getElementsByTagName("link")[0]||document.getElementsByTagName("title")[0];if(b){var c=document.createElement("link");c.rel="manifest";c.href=(a.platforms.chrome.serviceBase||"/")+"manifest.json";b.parentNode.insertBefore(c,b)}}navigator.serviceWorker.ready.then(function(b){b.pushManager.getSubscription().then(function(b){b?(C("granted"),u.$a(b,a.platforms.chrome.senderID)?
d.h("chrome",a.websiteID,u.H(b)):(b.unsubscribe(),u.subscribe())):(C(Notification.permission),"default"===Notification.permission?(d.h("chrome",a.websiteID,null),B.ea(r.askToSubscribe)):"denied"===Notification.permission?d.h("chrome",a.websiteID,null):u.subscribe())})["catch"](function(a){console.log("error fetching push notification subscription",a)})})}},H:function(a){a=a.endpoint.split("/");return a[a.length-1]},M:function(){return u.subscribe().then(function(a){B.F();return a})}},F;(function(){var a,
b;F={subscribe:function(a){var b=window.zaius.webPush.config;return new Promise(function(c){var e={action:"add_push_token",app_id:b.websiteID,zaius_alias_safari_token:a.deviceToken};e[b.websiteID+"_safari_push_tokens"]=a.deviceToken;d.h("safari",b.websiteID,a.deviceToken);zaius.event("push",e);c()})},initialize:function(c){b=window.zaius.webPush.config;"default"===c.permission?(a=d.a.trackerUrl+"/safari",b.webServiceURL&&(a=b.webServiceURL),B.ea(r.askToSubscribe)):"denied"===c.permission?d.h("safari",
b.websiteID,null):"granted"===c.permission&&d.h("safari",b.websiteID,c.deviceToken);C(c.permission)},M:function(){return new Promise(function(c){window.safari.pushNotification.requestPermission(a,b.websitePushID,{tracker_id:d.I,website_id:b.websiteID},function(a){"denied"===a.permission?(B.F(),c(a.permission)):"granted"===a.permission?F.subscribe(a).then(B.F).then(function(){c("subscribed")}):c(a.permission)})})}}})();var r=window.zaius.webPush={},v="serviceWorker"in navigator&&"chrome"in window?
"chrome":"safari"in window&&"pushNotification"in window.safari?"safari":null,C;r.ready=new Promise(function(a){C=a});var E=!1;try{E=window.location.href.startsWith("https://")}catch(a){}r.initialize=function(a){if(E)if(a)if(a.websiteID){if(!a.autoInit){var b=r.baseConfigs[a.websiteID];b&&(b=c.s(b),b.subscribeUI=c.j(b.subscribeUI||{},a.subscribeUI||{}),a=b)}r.config=a;"chrome"===v?a.platforms&&a.platforms.chrome&&a.platforms.chrome.enabled?navigator.serviceWorker.register((a.platforms.chrome.serviceBase||
"/")+"zaius-notification-service.js",{scope:"/"}).then(u.initialize)["catch"](function(a){console.log("error registering zaius-notification-service.js",a)}):r.remove():"safari"===v&&(a.platforms&&a.platforms.safari&&a.platforms.safari.enabled?a.websitePushID?(a=window.safari.pushNotification.permission(a.websitePushID),F.initialize(a)):console.log("zaius.webPush.initialize: missing required field `websitePushID`"):r.remove())}else console.log("zaius.webPush.initialize: missing required field `websiteID`");
else console.log("zaius.webPush.initialize: missing required config object parameter")};r.remove=function(){E&&"chrome"===v&&navigator.serviceWorker.getRegistration().then(function(a){if(a){var b=a.active;b&&b.scriptURL&&0<=b.scriptURL.indexOf("zaius-notification-service.js")&&a.unregister()}})};r.askToSubscribe=function(a){E&&("function"!==typeof a&&(a=null),r.ready=r.ready.then(function(b){if(v){var c="chrome"===v?u:"safari"===v?F:null;if("default"===b)return b=c.M(),a&&b.then(a),b;"denied"!==b&&
c.subscribe()}a&&a(b)}))};r.subscriptionStatus=function(a){"function"===typeof a&&(E?v&&r.ready.then(function(b){var c=d.D();a(b,c&&c.B)}):a("unsupported"))}}})();
})();

zaius.gtm||(zaius.gtm={});
zaius.gtm.ee||(zaius.gtm.ee={event:function(e,a,d){try{switch(d||(d=a.detail&&"detailView"||a.add&&"addToCart"||a.remove&&"removeFromCart"||a.purchase&&"purchase"||a.refund&&"refund"),d){case "detailView":this.productEvent(e,a.detail,"detail");break;case "addToCart":this.productEvent(e,a.add,"add_to_cart");break;case "removeFromCart":this.productEvent(e,a.remove,"remove_from_cart");break;case "purchase":this.purchase(e,a.purchase)}}catch(b){}},purchase:function(e,a){try{if(a&&a.actionField&&a.products){var d=
function(a,b){return isNaN(+a)?b:+a},b=a.actionField,f=a.products,c={order_id:b.id,total:d(b.revenue,0),subtotal:0,shipping:d(b.shipping,null),tax:d(b.tax,null),coupon_code:b.coupon||null,affiliation:b.affiliation||null,items:[]};b.revenue&&(c.subtotal=c.total-d(c.shipping)-d(c.tax));for(var h=0;h<f.length;h+=1){var k=f[h],g={product_id:k.id,price:d(k.price,0),quantity:d(k.quantity,1)};g.subtotal=g.quantity*g.price;c.items.push(g);b.revenue||(c.total+=g.subtotal,c.subtotal+=g.subtotal)}b.revenue||
(c.total+=c.shipping+c.tax);zaius.event("order",{action:"purchase",customer_id:e||null,order:c})}}catch(l){}},productEvent:function(e,a,d){try{if(a&&a.products){var b,f;for(f=0;f<a.products.length;f+=1)b=a.products[f],zaius.event("product",{action:d,customer_id:e||null,product_id:b.id||null}),zaius.entity("product",{product_id:b.id||null,name:b.name||null,brand:b.brand||null,category:b.category?b.category.replace(/\//g," > "):null})}}catch(c){}}});

zaius.initialize('DBTubRdZgjUxbnjHrIeLcA',{trackerUrl:'https://jumbe.zaius.com/v2'});